### ISSUE TITLE
Not able to achieve same accuracy as the paper

### ISSUE THREAD

**Issue by sachidanandvs** [erkil1452/touch#2]
I ran this code with both N = 5 and 7 and I was not able to achieve the same accuracy mentioned in the paper(89.4%).
My top1 val accuracy for cluster dataset is 78% and  top3 val accuracy for cluster dataset is 90.5%. Is the accuracy mentioned in the paper for top3 precision? or am I doing something wrong?

Thank you in advance

**Comment by erkil1452** [comment]
Are you referring to the object classification? I am looking at the results in Figure 2b and it seems that your numbers do match the paper quite well.

**Comment by sachidanandvs** [comment]
Sorry, my bad I looked at classifying objects with specific hand pose results.
