### ISSUE TITLE
checkpoint.pth.tar

### ISSUE THREAD

**Issue by DMX666** [erkil1452/touch#3]
where is checkpoint.pth.tar ? I find this in main.py file at 122 line. But I don't know where is it

**Comment by erkil1452** [comment]
I think we have not shared the trained weights. It is super fast to train so you do best to train your own. To bypass the error, just use parameter `--reset` which will skip loading the weights.

**Comment by erkil1452** [comment]
But if it helps, here are the classification weights trained using 1--8 input frames (see the paper): https://www.dropbox.com/s/v5nljhid2sf2h99/classification.zip?dl=0
